---
apiVersion: v1
kind: Service
metadata:
  name: to-nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-web-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:1.29
        ports:
        - containerPort: 80
          name: http-web-svc
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 120
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 200
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Value
        averageUtilization: 70
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argotest-ingress
  annotations:
    nginx.org/rewrites: "/"
spec:
  ingressClassName: nginx
  rules:
  - host: ingress.bexa.local
    http:
      paths:
      - path: /argotest
        pathType: Prefix
        backend:
          service:
            name: to-nginx
            port:
              number: 80
---
